# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test

on:
  push:
    branches: [ "master", "improve/update-github-actions" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LGPL.txt
      - README.md
      - THIRD-PARTY-LICENSE-README.md

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Add package source
        run: dotnet nuget add source ${{ github.workspace }}/Assemblies
      - name: Restore packages
        run: dotnet restore /property:Configuration="Debug vendor unsupported"
      - name: Build
        run: dotnet build --no-restore --configuration "Debug vendor unsupported" /property:BclBuildImported=Ignore
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration "Debug vendor unsupported"

